### ISSUE TITLE
support vimspector debug

### ISSUE THREAD

**Issue by 0x8f701** [voldikss/coc-cmake#10]
Ref: 

1. [vscode-cmake-tools debug](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md)
2. [coc-rust-analyzer vimspector support](https://github.com/fannheyward/coc-rust-analyzer/blob/master/src/commands.ts#L228-L317)
3. does clangd support codelens run? which gives instruction on some test items, I'm not sure at all
4. example vimspector config based on CodeLLDB
    ```json
    {
            "c/c++ - launch": {
            "adapter": "CodeLLDB",
            "configuration": {
                "request": "launch",
                "program": "${workspaceRoot}/${fileBasenameNoExtension}",
                "stopAtEntry": false
            },
            "breakpoints": {
                "exception": {
                    "cpp_throw": "Y",
                    "cpp_catch": "N"
                }
            }
    }
    ```
 5. [vscode-cpptools-integration](https://github.com/microsoft/vscode-cmake-tools/blob/develop/src/cpptools.ts)

**Comment by voldikss** [comment]
Thanks, this is a nice idea indeed. However I don't use vimspacetor and have no time to investigate and implement this feature. PR is welcome if possible but let me close this issue for the moment. I will reopen it in the future if necessary.
