### ISSUE TITLE
Extension not working (0.0.2)

### ISSUE THREAD

**Issue by Kshitij09** [voldikss/coc-cmake#5]
I just installed the extension (version: `0.0.2`) using
```shell
:CocInstall coc-cmake
```

and put the [configurations](https://github.com/voldikss/coc-cmake#configuration) in the `coc-settings.json`. I have also checked whether the extension is activated.

Is there any step I'm missing / doing wrong?

**Comment by voldikss** [comment]
Hi @Kshitij09 please make sure you have installed cmake executable.

**Comment by Kshitij09** [comment]
I had installed the cmake; it didn't work.

**Comment by voldikss** [comment]
What's the output of `cmake --help-command-list`?
