### ISSUE TITLE
Semantic highlight of CMake code

### ISSUE THREAD

**Issue by ghost** [voldikss/coc-cmake#6]
It would be pretty amazing if something could parse CMake syntax and communicate highlight regions for the plugin. Right now highlighting is done based on syntax file, which is 1) often out-of-date, 2) good enough for standard CMake code, but only introduces confusion when used in custom CMake code, e.g.:
![2020-10-18-103426_477x388_scrot](https://user-images.githubusercontent.com/46303212/96362444-a38c1800-112d-11eb-9c3d-d84b54b0d230.png)

**Comment by voldikss** [comment]
Sorry but this won't be supported in the extension.
